from .finops_prompts import (
    FINOPS_AGENT_BACKSTORY,
    FINOPS_AGENT_GOAL,
    FINOPS_AGENT_ROLE,
    FINOPS_SYSTEM_PROMPT,
)
from .judge_prompts import (
    FINOPS_JUDGE_BACKSTORY,
    FINOPS_JUDGE_GOAL,
    FINOPS_JUDGE_ROLE,
    SRE_JUDGE_BACKSTORY,
    SRE_JUDGE_GOAL,
    SRE_JUDGE_ROLE,
)
from .sre_prompts import (
    SRE_AGENT_BACKSTORY,
    SRE_AGENT_GOAL,
    SRE_AGENT_ROLE,
    SRE_SYSTEM_PROMPT,
)

__all__ = [
    "FINOPS_AGENT_ROLE",
    "FINOPS_AGENT_GOAL",
    "FINOPS_AGENT_BACKSTORY",
    "FINOPS_SYSTEM_PROMPT",
    "SRE_AGENT_ROLE",
    "SRE_AGENT_GOAL",
    "SRE_AGENT_BACKSTORY",
    "SRE_SYSTEM_PROMPT",
    "FINOPS_JUDGE_ROLE",
    "FINOPS_JUDGE_GOAL",
    "FINOPS_JUDGE_BACKSTORY",
    "SRE_JUDGE_ROLE",
    "SRE_JUDGE_GOAL",
    "SRE_JUDGE_BACKSTORY",
]



