"""Data contracts and schemas for Domain-Specialist Judge Agents."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class JudgeVerdict(str, Enum):
    """Verdict rendered by a Domain Judge Agent."""

    PASS = "PASS"        # Output meets all quality, mathematical, and safety criteria
    REVISE = "REVISE"    # Output has deficiencies or ungrounded claims; must be improved
    REJECT = "REJECT"    # Inviable, unsafe, or fundamentally flawed proposal


class DimensionScore(BaseModel):
    """Evaluation score for a specific rubric dimension."""

    name: str = Field(description="Name of the rubric evaluation dimension")
    score: int = Field(ge=0, le=100, description="Dimension score from 0 to 100")
    weight: float = Field(ge=0.0, le=1.0, description="Relative weight in overall calculation")
    notes: str = Field(default="", description="Detailed evaluation justification and observations")


class JudgeEvaluationReport(BaseModel):
    """Structured evaluation report generated by a Domain Judge Agent."""

    judge_role: str = Field(description="Role name of the Domain Judge")
    evaluated_agent: str = Field(description="Name/Role of the specialist agent being evaluated")
    overall_score: int = Field(ge=0, le=100, description="Weighted overall score from 0 to 100")
    verdict: JudgeVerdict = Field(description="Evaluation verdict: PASS, REVISE, or REJECT")
    dimension_scores: list[DimensionScore] = Field(default_factory=list, description="Per-dimension scores")
    hallucination_detected: bool = Field(default=False, description="True if unverified or invented numbers were found")
    unverified_claims: list[str] = Field(default_factory=list, description="Specific ungrounded statements or figures")
    critique_summary: str = Field(description="Executive summary of the evaluation feedback")
    actionable_improvements: list[str] = Field(
        default_factory=list, description="Concrete instructions for the agent to fix and improve the output"
    )
    iteration: int = Field(default=1, description="Reflection iteration number (1-based)")
    evaluation_timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), description="Timestamp when review was rendered"
    )

    def is_passing(self, min_score: int = 85) -> bool:
        """Helper to determine if the report meets passing threshold."""
        return self.verdict == JudgeVerdict.PASS and self.overall_score >= min_score and not self.hallucination_detected

